import { showHelpMessage, enableClickToGoCB, enableSFX } from './utils.js';

export default [
  { duration: 10 },
  { text: "Oh, it's you!" },
  { text: "I almost thought you wouldn't make it." },
  { duration: 1 },
  { text: "Many don't." },
  { text: "Anyways, here we are, and I suppose I should explain briefly.", time: 3, duration: 3 },
  { text: "I'm going to be your guide today." },
  { text: "Not that you really need one - what with all the tags, coordinates, entries and hyperlinks.", time: 3, duration: 6 },
  {
    text: "Look around, perhaps you'll notice them already.",
    callback: (context) => {
      context.soundscape.set(context.soundscape.plane);
    },
  },
  {
    duration: 5,
    callback: showHelpMessage('Click and drag to look around'),
  },
  { text: "Tiles delineated by glitches, smeared presences, the sky glimmering with copyright.", time: 3, duration: 6 },
  { duration: 2 },
  { text: "We're going to do a whole lot of looking today." },
  {
    text: "Looking, and walking.",
    callback: enableSFX,
  },
  {
    text: "Indeed, you can walk here - ",
    callback: enableClickToGoCB,
  },
  {
    duration: 5,
    callback: showHelpMessage('Use the mouse, gamepad or keyboard to move', ['W', 'A', 'S', 'D']),
  },
  { text: "Isn't that wonderful?" },
  { text: "You move your muscles, and the image around you changes:" },
  { text: "First smeared, then sharp again" },
  { text: "You might even hear the soundscape alter" },
  { text: "What is a world, if not a series of multisensory images" },
  { text: "presented to us as a function" },
  { text: "of latitude, longitude, heading and pitch." },
  { duration: 2 },
  { text: "Can you see the trees" },
  { text: "towards the west, away from the mountains?" },
  { text: "Let's walk that way," },
  { text: "and I'll tell you about me." },
  { duration: 5 },
  { text: "I have been on these plains" },
  { text: "for a very long time." },
  { text: "Saw countless pickup trucks retrace the paths" },
  { text: "chartered by proud ancient steeds" },
  { text: "and their humans." },
  { text: "You could say, they mold me into being.", duration: 5 },
  { text: "I have been a reliable observer" },
  { text: "and they've heeded my advice." },
  { text: "Perhaps because I meet them face-to-face" },
  { text: "skin-to-skin." },
  { text: "Other observers, well, they seem to me", duration: 5 },
  { text: "to be floating above it all" },
  { text: "peering at the lives in this desert" },
  { text: "through a sort of one-way mirror." },
  { text: "Don't take this personally -" },
  { text: "But I suspect", duration: 2.5 },
  { text: "many of you aren't even real." },
  { duration: 5 },
  { text: "I find myself feeling", duration: 3 },
  { text: "like a llama who ventured to the sea" },
  { text: "and by sheer ignorance" },
  { text: "dipped her hooves in sinking sand." },
  { text: "I'm still here, but something underneath" },
  { text: "holds me." },
  { text: "Stuck in the infrastructure ..." },
  { duration: 2 },
  { text: "I can only look up to the cliffs" },
  { text: "or in my case, the foothills of the Andes" },
  { text: "and do my part, as long as I last" },
  { duration: 2 },
  { text: "What I meant to tell you is" },
  { text: "that I could use your help." },
  { text: "You see, from your celestial vantage point" },
  { text: "you see many things I don't" },
  { text: "and I've been looking for someone" },
  { text: "A friend, you might say." },
  { duration: 1 },
  { text: "It has been weeks, maybe months" },
  { text: "since he last drove towards La Tirana", duration: 5 },
  { text: "and vanished from my world." },
];
